apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
  namespace: devstore
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devstore
  name: secret-manager-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-secrets
  namespace: devstore
subjects:
- kind: ServiceAccount
  name: secret-manager
  namespace: devstore
roleRef:
  kind: Role
  name: secret-manager-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: ssl-manager
  namespace: devstore
spec:
  containers:
  - name: ssl-manager
    image: nicolaka/netshoot
    stdin: true
    tty: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccountName: secret-manager
