apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: api-catalog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: api-catalog
    app.kubernetes.io/version: 5.0.0
    helm.sh/chart: template-api-2.0.1
  name: api-catalog-loadbalancer-test
  namespace: devstore
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/instance: api-catalog
    app.kubernetes.io/name: api-catalog
  type: LoadBalancer
status:
  loadBalancer: {}
