apiVersion: v1
kind: Pod
metadata:
  name: desenvolvedorio-app
  labels:
    app.kubernetes.io/name: desenvolvedorio-app
spec:
  containers:
  - name: checker
    image: alpine
    command: ['/bin/sh', '-c', 'if [ -f /workdir/calm.txt ]; then sleep 10000; else exit 1; fi']
    volumeMounts:
      - name: workdir
        mountPath: /workdir
  initContainers:
  - name: create
    image: alpine
    command: ['/bin/sh', '-c', "sleep 10 && cat > /workdir/calm.txt"]
    volumeMounts:
      - name: workdir
        mountPath: /workdir
  volumes: 
    - name: workdir
      emptyDir: {}

      