apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-multipleports
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api-multipleports
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: api-multipleports
      name: api-multipleports
    spec:
      containers:
      - image: desenvolvedorio/dominando-kubernetes:pod-lifecycle-running
        name: pod-lifecycle-running
      dnsPolicy: ClusterFirst
      restartPolicy: Always
