apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: scheduler-demo
  name: scheduler-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scheduler-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scheduler-demo
    spec:
      containers:
      - image: nginx:1.23.2
        name: nginx
        resources: {}
status: {}
