apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sqlserver
spec:
  replicas: 1
  selector:
    matchLabels:
      run: sqlserver
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: sqlserver
        environment: test
        tier: database
        app: dev-store
      name: database
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: Teste@123
        image: mcr.microsoft.com/mssql/server:2017-latest
        name: database
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
