apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rabbitmq
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: rabbitmq
        environment: test
        tier: queue
        app: dev-store
      name: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "devstore"
        - name: RABBITMQ_DEFAULT_PASS
          value: "devstore"
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always

