apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
  - name: load-generator
    image: busybox:1.28
    args:
    - /bin/sh
    - -c
    - while sleep 0.01; do wget -q -O- http://hpa-load-test-service/cpu; done
  restartPolicy: Never
