apiVersion: v1
data:
  CUSTOMCONNSTR_DefaultConnection: U2VydmVyPXBvc3RncmVzcWwuaW5mcmEuc3ZjO1BvcnQ9NTQzMjtEYXRhYmFzZT1EQlN0YXR1cztVc2VyIElkPXBvc3RncmVzO1Bhc3N3b3JkPXBvc3RncmVzOw==
kind: Secret
metadata:
  creationTimestamp: null
  name: status-connection
  namespace: devstore
