image:
  repository: desenvolvedorio/devstore-web-status
  tag: 1.3.1

readinessProbe:
  httpGet:
    path: /
    port: 443
    scheme: HTTPS
  initialDelaySeconds: 3
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: 443
    scheme: HTTPS
  initialDelaySeconds: 5
  periodSeconds: 10

service:
  port: 80
  targetPort: http

secretRefs:
  - status-connection

ingress:
  enabled: true
  hosts:
    - host: status.devstore.info
      paths:
        - path: /
          pathType: Prefix

pfx:
  enabled: true

environment:
  ASPNETCORE_URLS: http://+;https://+
  ENDPOINTS: "Identity API|https://api-identity/healthz-infra;BFF Checkout|https://api-bff-checkout/healthz;Frontend Web|http://web-mvc/healthz;Shopping Cart API|https://api-cart/healthz-infra;Catalog API|https://api-catalog/healthz-infra;Customer API|https://api-customer/healthz-infra;Billing API|https://api-billing/healthz-infra;Order API|https://api-orders/healthz-infra"