apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-update-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      run: pod-update-demo
  template:
    metadata:
      labels:
        run: pod-update-demo
    spec:
      containers:
      - image: desenvolvedorio/dominando-kubernetes:deployment-demo
        name: pod-update-demo
        env:
        - name: Shutdown
          value: "false"
        - name: Teste
          value: "teste"
