apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rabbitmq
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      run: rabbitmq
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: rabbitmq
        environment: test
        tier: queue
        app: dev-store
      name: rabbitmq
      namespace: infra
    spec:
      containers:
      - image: rabbitmq:3-management
        name: rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "devstore"
        - name: RABBITMQ_DEFAULT_PASS
          value: "devstore"
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: infra
spec:
  selector:
    run: rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672