apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: api-multipleports
  name: api-multipleports
spec:
  ports:
  - name: api
    port: 4200
    protocol: TCP
    targetPort: api
  - name: whoami
    port: 80
    protocol: TCP
    targetPort: whoami
  selector:
    app: api-multipleports
status:
  loadBalancer: {}