apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: api-catalog
  name: api-catalog
spec:
  containers:
  - image: desenvolvedorio/devstore-api-catalog:latest
    name: api-catalog
    env: 
    - name: ASPNETCORE_ENVIRONMENT
      value: Docker
    - name: CUSTOMCONNSTR_DefaultConnection
      value: "Server=172.17.0.4;Database=DSCatalog;MultipleActiveResultSets=true;User Id=sa;Password=Teste@123"
    - name: AppSettings__DatabaseType
      value: SqlServer
    - name: "USE_HTTPS_REDIRECTION"
      value: "false"
    - name: "MessageQueueConnection__MessageBus"
      value: "host=172.17.0.3:5672;publisherConfirms=true;timeout=30;username=devstore;password=devstore"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
