apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:3-management
    name: rabbitmq
    env:
    - name: RABBITMQ_DEFAULT_USER
      value: "devstore"
    - name: RABBITMQ_DEFAULT_PASS
      value: "devstore"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
