apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
spec:
  containers:
  - image: desenvolvedorio/dominando-kubernetes:volume-demo-create
    name: write
    imagePullPolicy: Always
    ports:
    - containerPort: 80
      protocol: TCP
  - image: desenvolvedorio/dominando-kubernetes:volume-demo-read
    name: read
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
    env:
    - name: ASPNETCORE_URLS
      value: http://*:8080
